### ISSUE TITLE
Search for Spotify songs

### ISSUE THREAD

**Issue by by7** [CS130-W20/team-B1#29]
## User Story
As a **Guest or Host**, I would like **A way to search for songs on Spotify** so that **It is convenient to add songs to queue**.

## Detailed Description
Create an API endpoint for the PartyQueue object to search for songs using the MusicService given a string query. 

## Acceptance Criteria
- [x] Given **A search query**, then **A list of matching songs is returned**

**Comment by bestvibes** [comment]
Handled by #31
